name: Linter
run-name: ${{ github.actor }} is linting the code

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    -
      name: Ceckout
      uses: actions/checkout@v3
    -
      name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    -
      name: Install packages
      run: |
        python3 -m pip install -e .[tests]
    -
      name: Linting
      run: make lint
